CREATE TABLE users (
  id INT AUTO_INCREMENT NOT NULL,
   email VARCHAR(50) NOT NULL,
   password VARCHAR(64) NOT NULL,
   CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users ADD CONSTRAINT uc_users_email UNIQUE (email);