CREATE TABLE books (
  id BIGINT AUTO_INCREMENT NOT NULL,
   title VARCHAR(255) NULL,
   author VARCHAR(255) NULL,
   CONSTRAINT pk_books PRIMARY KEY (id)
);

ALTER TABLE books ADD CONSTRAINT uc_526ced5a650ca7c51f1ea6cb0 UNIQUE (id);